Restaurant.create!(name: "McDonald's", category: "french", address: "75008 Singapore")
Restaurant.create!(name: "Watashiwa", category: "japanese", address: "75009 Tokyo")
Restaurant.create!(name: "WhatIsThis", category: "belgian", address: "75010 Paris")
Restaurant.create!(name: "JesusRedWine", category: "italian", address: "75011 Mexico")
Restaurant.create!(name: "LaoGanMa", category: "chinese", address: "75012 Jesus Alley")
